# Generated by Django 4.1 on 2022-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20201023_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='card_completed',
            field=models.BooleanField(default=False),
        ),
    ]
