# Generated by Django 4.1 on 2022-09-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_item_card_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
    ]
